### Get movies
GET http://localhost:1234/movies

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genre=ACTION

### Get movie by ID
GET http://localhost:1234/movies/15e7fb9d-ad87-11ef-8319-3024a9944028

### Create a movie
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The best film ever",
  "year": 2001,
  "director": "Jumanji",
  "duration": 120,
  "poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
  "genre": [
    "Adventure"
  ],
  "rate": 10
}

### Update a movie
PATCH http://localhost:1234/movies/15e7fb9d-ad87-11ef-8319-3024a9944028
Content-Type: application/json

{
  "year": 2008
}

### Delete a movie
DELETE http://localhost:1234/movies/15e7f7f3-ad87-11ef-8319-3024a9944028